import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:intl/date_symbol_data_local.dart';

import 'core/theme/app_theme.dart';
import 'features/workout/data/models/exercise.dart';   // <-- MODEL IMPORTS
import 'features/workout/data/models/workout_set.dart';
import 'features/workout/data/models/workout_history.dart';
import 'features/workout/data/models/workout_routine.dart';
import 'features/workout/presentation/screens/home_screen.dart';

void main() async { // <-- 2. MADE ASYNC
  // Initialize Flutter manually (Required because we need async operations)
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Hive
  await Hive.initFlutter();
  
  // Register adapters (Generated by build runner)
  Hive.registerAdapter(ExerciseAdapter());
  Hive.registerAdapter(WorkoutSetAdapter());
  Hive.registerAdapter(WorkoutHistoryAdapter());
  Hive.registerAdapter(WorkoutRoutineAdapter());
  
  // Open boxes (Tables)
  await Hive.openBox<Exercise>('exercises');
  await Hive.openBox<WorkoutHistory>('history');
  await Hive.openBox<WorkoutRoutine>('routines');

  await initializeDateFormatting('tr_TR', null);

  runApp(const ProviderScope(child: FitnessApp()));
}

class FitnessApp extends StatelessWidget {
  const FitnessApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      home: const HomeScreen(),
    );
  }
}